### ISSUE TITLE
[Suggestion] Don't include bots in list of contributors

### ISSUE THREAD

**Issue by itaditya** [probot/weekly-digest#10]
@aps120797 your creating is looking wonderful. 

I was checking this issue it created https://github.com/aps120797/playground/issues/22 . In it the CONTRIBUTORS section lists the `weekly-digest` bot as a contributor. I think bots shouldn't be included in the list. Let me know what you think.

**Comment by aps120797** [comment]
Nice catch! I have seen that and have that in my mind to remove it. 😄

**Comment by aps120797** [comment]
I have removed bots and their activities to be published by weekly-digest .

I am closing this issue now. 😄
