### ISSUE TITLE
Bot doesn't color the weekly digest label to the assigned color

### ISSUE THREAD

**Issue by aps120797** [probot/weekly-digest#15]
The maintainers of [thefrontside](https://github.com/thefrontside/) have installed their application in one of their repository thefrontside/emberx-xml-http-request (https://github.com/thefrontside/emberx-xml-http-request). 
It appears that the application is working and has opened an issue: https://github.com/thefrontside/emberx-xml-http-request/issues/14

But I can see it hasn't coloured the weekly-digest label as it was needed. 😕

**Comment by aps120797** [comment]
This is something related with this line: 
https://github.com/probot/weekly-digest/blob/b304ada680d489724fd82da653d40963447ab6af/index.js#L19

**Comment by aps120797** [comment]
And something related to this file:
https://github.com/probot/weekly-digest/blob/master/lib/markdown/createWeeklyDigestLabel.js

**Comment by aps120797** [comment]
@gr2m , I discussed about this with @wilhelmklopp yesterday, he said that it was because in the repository where the app, the master branch is currently [protected](https://help.github.com/articles/about-protected-branches/).
It was also the reason why the bot wasn't able to create `.github/weekly-digest.yml` in the master (which I am going to change to open a PR now instead). See #17 and #16 

I can fix #16 by creating a PR. How can I make this work at the time of creating label if the branch master is protected. 😕

**Comment by wilhelmklopp** [comment]
Protected branches will only affect commits/pushes. Label creation should work as expected even if there are protected branches :D

**Comment by Robdel12** [comment]
Woops! I'm sorry I couldn't circle back to this sooner. I think you might be seeing bugs with Frontside related things because at first I accidentally added it to _all_ of our repos. I wanted to test it out on a specific repo :)

I wish I could have caught this earlier :( Kind of sent you on a chase

**Comment by aps120797** [comment]
So far, I am not seeing this problem happening in this in any other repository.
I will be closing this PR for now. If it happens again, I will reopen this PR.
Thanks. 😄
