### ISSUE TITLE
Add helpful text if section is empty

### ISSUE THREAD

**Issue by gr2m** [probot/weekly-digest#20]
Example: https://github.com/gr2m/sandbox/issues/44

There were no closed issues:

![image](https://user-images.githubusercontent.com/39992/41482399-5c15784a-708a-11e8-8b81-66e91b8c63ca.png)

It’s called the "blank slate", think of what content looks like if there is no data. The Getting Real has a good chapter on it if you are interested :) https://basecamp.com/books/getting-real Old-ish book but great one, I’d recommend to read it anyway, it’s quite short

**Comment by itaditya** [comment]
thanks a lot @gr2m, watching this repo is quite beneficial :100:

**Comment by aps120797** [comment]
Yeah @gr2m, I have seen this thing happening in a repo where weekly-digest bot has been installed. While developing, I fixed empty problem with PRs, but I guess I forgot to do it for Issues section.
Will do so in the next commit.

**Comment by aps120797** [comment]
Oops, sorry, closed by mistake.

**Comment by aps120797** [comment]
I have fixed this in this commit: https://github.com/probot/weekly-digest/commit/43576c0dfa5a4a2686c029c4fc44d02a0e2aaf0f
