### ISSUE TITLE
PULL REQUESTS says a pr was "proposed" this week, but it was only updated 

### ISSUE THREAD

**Issue by gr2m** [probot/weekly-digest#21]
See https://github.com/gr2m/sandbox/issues/44

> This week, 1 pull request has been proposed, which is still open.

Maybe it’s just the wording? It cold say "1 pull request has been updated" instead, for example?

**Comment by aps120797** [comment]
I have seen this bug also.
But i think i will make this bug as a feature in the next update. 
I will create two different section, one for Open PRs and another for active PRs. 
I have this in mind, what you say @gr2m?

**Comment by gr2m** [comment]
works for me 👍 It'd also be an option to just accept that this is a known issue and get back to it later, it’s not something that is critical and needs fixing right away I think, it’s not blocking anything. Your call 👍

**Comment by abhijeetps** [comment]
This issue has been fixed. Thanks @gr2m ! 😄
