### ISSUE TITLE
Setup semantic release in the application

### ISSUE THREAD

**Issue by abhijeetps** [probot/weekly-digest#22]
Hi mentors, 
I think I am about to release next versions of the app. As you asked me to work with sematic release this week, a guidance for how can release and deploy probot application will be really helpful.

I am thinking to release and deploy next version of weekly-digest using semantic release.

What you say?
cc: @gr2m , @wilhelmklopp

**Comment by gr2m** [comment]
[semantic-release](https://github.com/semantic-release/semantic-release) will let you publish a new release on GitHub where you can put changelogs. Usually semantic-release is used to also publish a package to npm which maybe you don’t need to do for weekly-digest, I don’t think it’ll be used as  a dependency in another node project?

You can start by setting up the repository using https://github.com/semantic-release/cli. After that you can adopt the `package.json` to disable the publishing to npm. Add these lines: https://github.com/wip/app/blob/88f6c675f10baabc40b62b77ff7e7fcce92492f8/package.json#L58-L62 (it overrides the default configuration and removes all the npm-related tasks)

You’ll still need to deploy the app to glitch manually, but we can setup continuous deployment next week :)

Let me know if you have any questions

**Comment by abhijeetps** [comment]
Semantic release has been setup.
