### ISSUE TITLE
[Suggestion] Split one big issue description into small comments

### ISSUE THREAD

**Issue by itaditya** [probot/weekly-digest#24]
@aps120797 as the number of statistics displayed in the digest increases more requests will be made in order to gather data. Due to this the bot will have to do a lot of waiting before showing the weekly digest to the community.

What I suggest is to split the statistics into individual comments on the weekly-digest issue. This way when a whole statistic section is complete then it is shown on github. Concurrently the bot can work on gathering data for other statistics also.

Just a thought, maybe not worth it. Let me know your thoughts. /cc @gr2m

**Comment by itaditya** [comment]
For better explanation, suppose this is the weekly digest issue opened by bot. Then the bot will also make the following comments ->

**Comment by itaditya** [comment]
![image](https://user-images.githubusercontent.com/15871340/41557966-fac27838-735c-11e8-9824-9111b96a19fd.png)

**Comment by itaditya** [comment]
![image](https://user-images.githubusercontent.com/15871340/41557990-0ef34daa-735d-11e8-947c-c05683607a0b.png)

**Comment by itaditya** [comment]
![image](https://user-images.githubusercontent.com/15871340/41558006-1bea9c5c-735d-11e8-8901-a84a2570c45e.png)

**Comment by itaditya** [comment]
another advantage of this is suppose fetching commits takes time, then the comment for that will be created later, however other statistics like Issues and Pull Requests will be displayed on github when they're available

**Comment by gr2m** [comment]
I don’t think that splitting up the comments is a good idea right now. I’d focus on other things first

**Comment by aps120797** [comment]
I too think the same, @gr2m . I was expecting for your response for now.

Closing this issue for now.
