### ISSUE TITLE
Should nock be removed from the dependencies?

### ISSUE THREAD

**Issue by wilhelmklopp** [probot/weekly-digest#53]
👋 Just noticed this. Should nock be moved to devdependencies or be removed entirely since it's not in use at the moment?

https://github.com/probot/weekly-digest/blob/f1787ffb1b1ed703e030545e9d08e2b92d03a90e/package.json#L20

**Comment by abhijeetps** [comment]
I think I will keep nock in _package.json_.
Very soon, I will be adding some more tests using nock in my app. ✅
