### ISSUE TITLE
Content of .github/config.yml for Weekly Digest

### ISSUE THREAD

**Issue by abhijeetps** [probot/weekly-digest#6]
Hey all,
I am planning to use `.github/config.yml` to save repository based configurations for Weekly Digest.

What should be the contents of the files of the weekly digest and what configurations should the file have?

**Comment by gr2m** [comment]
I guess it's your plan anyway, but I’d suggest to start out without any configuration.

I’m also not sure about the latest state of configuration, but usually I’d do `.github/<app name>.yml`, so `.github/weekly-digest.yml` in your case? I might be wrong on that one though :) 

For the future, things that I’d like to be configurable are

- blocks to include in the digest, where each block would be a feature that `weekly-digest` supports
- repository / issue where I’d like the digest to be posted. Some project use multiple repositories and it would be nice to install it on all of them but have the digest be posted in only a single issue, for example

**Comment by abhijeetps** [comment]
Contents of _.github/weekly-digest.yml_ is shared here: https://github.com/probot/weekly-digest/blob/master/docs/configuration.md
